services:
  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool_instance
    ports:
      - "3301:3301"
    volumes:
      - /data/dir/on/host:/var/lib/tarantool
      - ./docker/init.lua:/usr/share/tarantool/init.lua
    environment:
      TARANTOOL_MEMORY_LIMIT: 512MB
      TARANTOOL_USER: admin
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: grpc_server
    ports:
      - "8081:8081"
    depends_on:
      - tarantool
    environment:
      TARANTOOL_HOST: tarantool_instance
      TARANTOOL_PORT: 3301
    restart: unless-stopped