spring:
  tarantool:
    host: localhost
    port: 3301
    username: tarantool
    password: tarantool
    connection:
      retries: 5
      timeout: 1000 # in milliseconds

grpc:
  server:
    port: 8080
